version: 1.0.{build}
image: Ubuntu-latest

environment:
  matrix:
    - PYTHON: "3.11"
    - PYTHON: "3.10"

before_install:
  - cd flaskapp
  - chmod +x st.sh

install:
  - pip install -r ../requirements.txt
  - pip install requests gunicorn

build_script:
  - ./st.sh
