version: 1.0.{build}

environment:
  matrix:
    - TOXENV: py38

before_build:
  - ps: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
  - bash: ./flaskapp/st.sh

install:
  - pip install flask
  - pip install gunicorn

build_script:
  - cd flaskapp
  - ./st.sh
