version: 1.0.{build}

before_build:
  - bash: ./flaskapp/st.sh

install:
  - python -m pip install --upgrade pip
  - pip install flask
  - pip install gunicorn
  - pip install requests
build_script:
  - cd flaskapp
  - powershell -ExecutionPolicy Bypass -File ./st.ps1
