version: 1.0.{build}

environment:
  matrix:
    - TOXENV: py38

before_build:
  - bash: ./flaskapp/st.sh

install:
  - pip install flask
  - pip install gunicorn
  - pip3 install requests
build_script:
  - cd flaskapp
  - ./st.sh
