version: 1.0.{build}

before_build:
  - bash: ./flaskapp/st.sh

install:
  - python -m pip install --upgrade pip
  - pip install flask
  - pip install gunicorn
  - pip install requests
  - pip3 install flask-bootstrap
- pip3 install flask-wtf
- pip3 install pillow
- pip3 install tensorflow==2.17.0
- pip3 install keras 
build_script:
  - cd flaskapp
  - powershell -ExecutionPolicy Bypass -File ./st.ps1
